### ISSUE TITLE
Stereotype changes `CPython` behaviour

### ISSUE THREAD

**Issue by igor-susic** [petee-d/stereotype#18]
When you type hint an attribute, because of the magic the library does in the background you cannot use `class` attributes anymore as expected.

Code to reproduce the issue:

Version used: `1.4.2`

```Python
from stereotype import Model

some_configuration: dict = {"KEY": "value"}

class TestClass(Model):
    some_attr: str
    CLASS_ATTR: str = "KEY"
    @classmethod
    def from_config(cls, param: dict):
        data = param.get(cls.CLASS_ATTR)  # Value of  cls.CLASS_ATTR is lost here
        return cls({"some_attr": data})


TestClass.from_config(some_configuration)
```

To fix this one would need to remove type hint from `CLASS_ATTR: str = "KEY"` and the docs says:

> All public class attributes that have a type annotation (i.e. the attribute name is followed with a colon) will be converted to model fields, i.e. they can be deserialized from input, serialized to output or be validated. See [Fields](https://stereotype.readthedocs.io/en/latest/fields.html#fields) for information about what types are supported.

> Attributes without a type annotation will not be treated as fields and are just static class members. Same applies for attributes with a ClassVar annotation.

Which is somewhat pointing to this but you don't really expect to lose some `CPython` functionality over type hint, or that type hint decides the functionality, it's kinda weird 👁️

Is this something to stay by design or was it overlooked?

**Comment by petee-d** [comment]
Yes, it's definitely by design, the most important core mechanics. :) The whole point of the library is to convert public class attributes with type annotations to **model fields** - instance attributes for which the library handles conversion and validation. Dataclasses, a Python built-in, do pretty much the same thing, same for similar libraries like Pydantic and attrs, so I wouldn't call it weird. The change of usual class attribute behavior is done in favor of ease of use and (if you know what the library is for) readability.

Also, as the documentation you quoted says, if you want a class attribute with a type annotation, you can do the same you would do for dataclasses - use [`ClassVar`](https://docs.python.org/3/library/typing.html#typing.ClassVar), a Python built-in created specifically for this purpose. Here is an example:

```python
from typing import ClassVar
from stereotype import Model

class MyModel(Model):
    model_field: str  # Model field
    CLASS_ATTR: ClassVar[str] = "KEY"  # Class attribute, because of ClassVar, case doesn't matter
    _private: str = "xyz"  # Class attribute, because of leading underscore
    no_hint = "xyz"  # Class attribute, because of missing type hint
```

**Comment by igor-susic** [comment]
Ah, ok I see now. Yes indeed `pydantic` has the same behaviour while `dataclass` does not, it keeps what you would expect from `Python` thanks for the answer.
